/* eslint-disable */
// This file was generated by script
// this file is used to generate icon names from files within this directory
// icons are used in Icon component

import close from './close.svg';
import description from './description.svg';
import dropdown from './dropdown.svg';
import flagGb from './flag-gb.svg';
import flagUa from './flag-ua.svg';
import fullscreen from './fullscreen.svg';
import gear from './gear.svg';
import moon from './moon.svg';
import planet from './planet.svg';
import sun from './sun.svg';

const icons = {
  'close': close,
  'description': description,
  'dropdown': dropdown,
  'flag-gb': flagGb,
  'flag-ua': flagUa,
  'fullscreen': fullscreen,
  'gear': gear,
  'moon': moon,
  'planet': planet,
  'sun': sun,
};

export default icons;
