/* eslint-disable */
// This file was generated by script
// this file is used to generate icon names from files within this directory
// icons are used in Icon component

import battery from './battery.svg';
import moon from './moon.svg';
import sun from './sun.svg';

const icons = {
  'battery': battery,
  'moon': moon,
  'sun': sun,
};

export default icons;
